// active connection to DB
const db = require("./client");

// seed data (if required, force = true):
const sync = async (force = false) => {
  
  try {
      if (force) {
          await db.query(`
            DROP TABLE IF EXISTS users;
          `);

          await db.query(`
            create table users (
              user_id INTEGER primary key generated by default as identity,
              user_name varchar(50) not null unique,
              role varchar default 'user'
            );
          `)
      }
  } catch (error) {
    throw error;
  }

};

module.exports = sync;